Models/chronic/MedicationDosageAdjustment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace CodeMed.Models.chronic
{
    public class MedicationDosageAdjustment
    {
        [Key]
        public int Id { get; set; }
        public string? Doctor { get; set; }
        public string? Patient { get; set; }
        public string? MedicationName { get; set; }
        public string? Dose { get; set; }
        public string? RoutesOfAdministration { get; set; }
        public string? AdjustmentReason { get; set; }
        public string? NewMedication { get; set; }
        public string? ProposedDose { get; set; }
        public string? ProposedRouteOfAdministration { get; set; }
        public string? Warning { get; set; }
        public string? SpecialInstructions { get; set; }
        public string? ContactNumber { get; set; }
        public string? EmailAddress { get; set; }
        public DateTime Date { get; set; }
    }
}

Models/chronic/MedicationFeedback.cs
using System.ComponentModel.DataAnnotations;

namespace CodeMed.Models.chronic
{
    public class MedicationFeedback
    {
        [Key]
        public int? Id { get; set; }
        public string? Patient { get; set; }
        public string? MedicationName { get; set; }
        public string? Dose { get; set; }

        public DateTime Date { get; set; }

        public string? SideEffects { get; set; }
        public string? Effectiveness { get; set; }
    }
}

Models/chronic/MedicationHistory.cs
using System.ComponentModel.DataAnnotations;

namespace CodeMed.Models.chronic
{
    public class MedicationHistory
    {
        [Key]
        public int Id { get; set; }
        public string? Doctor { get; set; }
        public string? Patient { get; set; }

        [Required(ErrorMessage = "Chronic Condition is required")]
        public string? ChronicCondition { get; set; }

        [Required(ErrorMessage = "Allergies is required")]
        public string? Allergies { get; set; }

        [Required(ErrorMessage = "Family History is required")]
        public string? FamilyHistory { get; set; }

        public string? MedicationName { get; set; }

        [Required(ErrorMessage = "Dose is required")]
        public string? Dose { get; set; }

        [Required(ErrorMessage = "Medication Reason is required")]
        public string? MedicationReason { get; set; }
    }
}

Models/chronic/MedicationPrescription.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace CodeMed.Models.chronic
{
    public class MedicationPrescription
    {
        [Key]
        public int PrescriptionID { get; set; }
        [Required(ErrorMessage = "Doctor is required")]
        public string? Doctor { get; set; }
        public string? Patient { get; set; }

        [Required(ErrorMessage = "Chronic Condition is required")]
        public string? ChronicCondition { get; set; }

        [Required(ErrorMessage = "Medication Name is required")]
        public string? MedicationName { get; set; }

        [Required(ErrorMessage = "Dose is required")]
        public string? Dose { get; set; }

        [Required(ErrorMessage = "Route of Administration is required")]
        public string? RoutesOfAdministration { get; set; }

        [Required(ErrorMessage = "Warning is required")]
        public string? Warning { get; set; }

        [Required(ErrorMessage = "Special Instructions are required")]
        public string? SpecialInstructions { get; set; }

        [Required(ErrorMessage = "Contact Number is required")]
        public string? ContactNumber { get; set; }

        [Required(ErrorMessage = "Email Address is required")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string? EmailAddress { get; set; }

        [Required(ErrorMessage = "Prescription Date is required")]
        [DataType(DataType.Date)]
        public DateTime PrescriptionDate { get; set; }
    }
}

Models/chronic/MedicationRefill.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace CodeMed.Models.chronic
{
    public class MedicationRefill
    {
        [Key]
        public int MedicationRefillID { get; set; }
        [Required]
        public string? Doctor { get; set; }
        public string? Patient { get; set; }
        [Required]
        public string? ContactNumber { get; set; }
        [Required]
        public string? PhysicalAddress { get; set; }
        [Required]
        public string? MedicationName { get; set; }
        [Required]
        public string? Dose { get; set; }
        [Required]
        public string? RoutesOfAdministration { get; set; }
        [Required]
        public string? DeliveryOptions { get; set; }
        [Required]
        public DateTime RefillDate { get; set; }
    }
}

Controllers/ChronicMedicationController.cs
using CodeMed.Areas.Identity.Pages.Account;
using CodeMed.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data;
using Microsoft.Data.SqlClient;
using System.Numerics;
using System;
using System.Linq;
using CodeMed.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using CodeMed.Models.Prenatal.Doctor;
using CodeMed.Models.chronic;

namespace CodeMed.Controllers
{
    public class ChronicMedicationController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ApplicationDbContext _db;

        public ChronicMedicationController(IConfiguration configuration, ApplicationDbContext db)
        {
            _configuration = configuration;
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult PrescriptionsConditions()
        {
            using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("DefaultConnection")))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("sp_medicalPrescriptionsConditions", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

                    // Retrieve the Obstetrician ID from session data
                    string ObstetricianId = HttpContext.Session.GetString("Id");

                    if (!string.IsNullOrEmpty(ObstetricianId))
                    {
                        // Use ObstetricianId to retrieve the value you want to pass as a parameter
                        string concatenatedName = $"{HttpContext.Session.GetString("FirstName")} {HttpContext.Session.GetString("LastName")}";

                        // Check if the concatenatedName is not null or empty before adding it as a parameter
                        if (!string.IsNullOrEmpty(concatenatedName))
                        {
                            command.Parameters.Add(new SqlParameter("@Doctor", concatenatedName));
                        }
                        else
                        {
                            // Handle the case where the name is missing or empty
                            // You can return a placeholder value for PatientName or redirect the user to a different page.
                            // For example:
                            string placeholderPatientName = "Name Not Found";
                            return View(placeholderPatientName);
                        }

                        using (SqlDataAdapter adapter = new SqlDataAdapter(command))
                        {
                            DataTable dataTable = new DataTable();
                            adapter.Fill(dataTable);
                            return View(dataTable);
                        }
                    }
                    else
                    {
                        // Handle the case where the ObstetricianId is missing or empty
                        // You can return an error message or redirect the user to a different page.
                        // For example:
                        return RedirectToAction("Error");
                    }
                }
            }
        }

        public IActionResult TotalPresc()
        {
            using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("DefaultConnection")))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("sp_doctorTotalPresc", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

                    // Retrieve the Obstetrician ID from session data
                    string ObstetricianId = HttpContext.Session.GetString("Id");

                    if (!string.IsNullOrEmpty(ObstetricianId))
                    {
                        // Use ObstetricianId to retrieve the value you want to pass as a parameter
                        string concatenatedName = $"{HttpContext.Session.GetString("FirstName")} {HttpContext.Session.GetString("LastName")}";

                        // Check if the concatenatedName is not null or empty before adding it as a parameter
                        if (!string.IsNullOrEmpty(concatenatedName))
                        {
                            command.Parameters.Add(new SqlParameter("@Doctor", concatenatedName));
                        }
                        else
                        {
                            // Handle the case where the name is missing or empty
                            // You can return a placeholder value for PatientName or redirect the user to a different page.
                            // For example:
                            string placeholderPatientName = "Name Not Found";
                            return View(placeholderPatientName);
                        }

                        using (SqlDataAdapter adapter = new SqlDataAdapter(command))
                        {
                            DataTable dataTable = new DataTable();
                            adapter.Fill(dataTable);
                            return View(dataTable);
                        }
                    }
                    else
                    {
                        // Handle the case where the ObstetricianId is missing or empty
                        // You can return an error message or redirect the user to a different page.
                        // For example:
                        return RedirectToAction("Error");
                    }
                }
            }
        }

        public IActionResult medicalPrescriptions()
        {
            using (SqlConnection connection = new SqlConnection(_configuration.GetConnectionString("DefaultConnection")))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("sp_medicalPrescriptions", connection))
                {
                    command.CommandType = CommandType.StoredProcedure;

                    // Retrieve the Obstetrician ID from session data
                    string ObstetricianId = HttpContext.Session.GetString("Id");

                    if (!string.IsNullOrEmpty(ObstetricianId))
                    {
                        // Use ObstetricianId to retrieve the value you want to pass as a parameter
                        string concatenatedName = $"{HttpContext.Session.GetString("FirstName")} {HttpContext.Session.GetString("LastName")}";

                        // Check if the concatenatedName is not null or empty before adding it as a parameter
                        if (!string.IsNullOrEmpty(concatenatedName))
                        {
                            command.Parameters.Add(new SqlParameter("@Doctor", concatenatedName));
                        }
                        else
                        {
                            // Handle the case where the name is missing or empty
                            // You can return a placeholder value for PatientName or redirect the user to a different page.
                            // For example:
                            string placeholderPatientName = "Name Not Found";
                            return View(placeholderPatientName);
                        }

                        using (SqlDataAdapter adapter = new SqlDataAdapter(command))
                        {
                            DataTable dataTable = new DataTable();
                            adapter.Fill(dataTable);
                            return View(dataTable);
                        }
                    }
                    else
                    {
                        // Handle the case where the ObstetricianId is missing or empty
                        // You can return an error message or redirect the user to a different page.
                        // For example:
                        return RedirectToAction("Error");
                    }
                }
            }
        }

        public IActionResult MedicationDosageAdjustment()
        {
            GetPatients();
            MedicationDosageAdjustment Date = new MedicationDosageAdjustment()
            {
                Date = DateTime.Now,
            };
            return View(Date);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MedicationDosageAdjustment(MedicationDosageAdjustment adjustment)
        {
            if (ModelState.IsValid)
            {
                _db.adjustments.Add(adjustment);
                _db.SaveChanges();
                TempData["success"] = "Medication Dosage Adjustment saved successfully";
                return RedirectToAction("MedicationDosageAdjustment");
            }
            return View(adjustment);
        }
        public IActionResult MedicationFeedback()
        {
            GetPatients();
            MedicationFeedback Date = new MedicationFeedback()
            {
                Date = DateTime.Now,
            };
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult MedicationFeedback(MedicationFeedback medicationFeedback)
        {
            if (ModelState.IsValid)
            {
                _db.feedbacks.Add(medicationFeedback);
                _db.SaveChanges();
                TempData["success"] = "Medication Feedback saved successfully";
                return RedirectToAction("MedicationFeedback");
            }
            return View(medicationFeedback);
        }
        public IActionResult MedicationHistory()
        {
            GetPatients();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/ChronicMedication/About.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        h1 {
            font-size: 40px;
            font-weight: bold;
        }

        h2 {
            font-size: 26px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>Chronic Medication</h1>
    <p>Chronic medication refers to long-term prescription drugs that are used to manage chronic or ongoing medical conditions. These medications are typically taken regularly over an extended period to control symptoms, slow down disease progression, and improve the overall quality of life for individuals with chronic conditions.</p>

    <h2>Types of Chronic Medications</h2>
    <p>There is a wide range of chronic medications available, tailored to treat specific chronic conditions. Some common types of chronic medications include:</p>
    <ul>
        <li>Antihypertensives: Medications used to treat high blood pressure and reduce the risk of cardiovascular complications.</li>
        <li>Antidiabetic Agents: Medications that help manage blood sugar levels in individuals with diabetes, such as insulin and oral hypoglycemic drugs.</li>
        <li>Anticoagulants: Medications used to prevent the formation of blood clots and reduce the risk of stroke or heart attacks.</li>
        <li>Immunosuppressants: Drugs that suppress the immune system to prevent rejection of transplanted organs or manage autoimmune conditions.</li>
        <li>Analgesics: Pain-relieving medications used to manage chronic pain, such as nonsteroidal anti-inflammatory drugs (NSAIDs) or opioids.</li>
        <li>Antidepressants: Medications prescribed to manage symptoms of depression and other mental health conditions.</li>
        <li>Cholesterol-Lowering Medications: Drugs that help lower cholesterol levels and reduce the risk of heart disease.</li>
        <li>Anti-inflammatory Drugs: Medications that reduce inflammation and alleviate symptoms in conditions like arthritis or inflammatory bowel disease.</li>
    </ul>

    <h2>Importance of Chronic Medication</h2>
    <p>Chronic medication plays a crucial role in managing chronic diseases and improving health outcomes. Here are some key reasons why chronic medication is important:</p>
    <ul>
        <li>Disease Control: Chronic medications help control symptoms and prevent disease progression, allowing individuals to maintain stable health and functionality.</li>
        <li>Quality of Life Improvement: By managing symptoms and reducing the impact of chronic conditions, medication can improve the overall quality of life for individuals, allowing them to engage in daily activities and pursue their goals.</li>
        <li>Prevention of Complications: Chronic medications can help prevent complications and minimize the risk of further health issues associated with chronic conditions.</li>
        <li>Long-Term Health Maintenance: By consistently taking chronic medications as prescribed, individuals can better manage their conditions, leading to better long-term health outcomes.</li>
        <li>Improved Independence: Proper medication management empowers individuals to take an active role in their health, promoting independence and self-care.</li>
        <li>Enhanced Well-Being: Effective chronic medication use can alleviate symptoms, reduce pain, and promote mental well-being, contributing to an overall sense of wellness.</li>
    </ul>

    <h2>Medication Adherence</h2>
    <p>Adherence to prescribed chronic medication is vital for achieving optimal health outcomes. Here are some tips for medication adherence:</p>
    <ul>
        <li>Follow the Prescription Instructions: Take the medication as prescribed by your healthcare provider, following the recommended dosage, frequency, and duration.</li>
        <li>Set Reminders: Use alarms, medication organizers, or smartphone apps to help you remember when to take your medications.</li>
        <li>Refill Medications on Time: Ensure you have an adequate supply of medications by refilling them before they run out.</li>
        <li>Communicate with your Healthcare Provider: Inform your healthcare provider about any challenges or concerns you may have regarding your medication regimen.</li>
        <li>Understand Potential Side Effects: Be aware of the possible side effects of your medications and discuss them with your healthcare provider.</li>
        <li>Engage in Regular Follow-ups: Attend regular check-ups with your healthcare provider to monitor your condition and discuss any necessary adjustments to your medication regimen.</li>
        <li>Seek Support: Reach out to healthcare professionals, support groups, or loved ones for assistance and encouragement in managing your chronic medication.</li>
    </ul>
    <h2>Conclusion</h2>
    <p>Chronic medication is an essential component of managing chronic conditions, improving quality of life, and preventing complications. By adhering to prescribed medication regimens and working closely with healthcare providers, individuals can effectively manage their chronic conditions and achieve better health outcomes.</p>
</body>
</html>

Views/ChronicMedication/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Chronic Medication System Dashboard</title>
    <style>
        body {
            color: #fff;
            font-family: Arial, sans-serif;
            background-color: #0a0a2a;
        }

        h1 {
            text-align: center;
            padding-top: 50px;
            margin-bottom: 20px;
            color: blue;
        }

        #dashboardContainer {
            max-width: 80%;
            margin: 0 auto;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .dashboardItem {
            border: 2px solid #fff;
            border-radius: 5px;
            padding: 20px;
            margin: 10px;
            flex-basis: 30%;
            text-align: center;
            background-color: purple;
        }

            .dashboardItem a {
                display: block;
                color: #fff;
                text-decoration: none;
                margin-bottom: 10px;
                padding: 10px;
                border: 1px solid #fff;
                border-radius: 5px;
            }

                .dashboardItem a:hover {
                    background-color: #ff4081;
                }
    </style>
</head>
<body>
    <h1>Chronic Medication System Dashboard</h1>

    <div id="dashboardContainer">
        <div class="dashboardItem">
            <h2>Book Consultation</h2>
            <a asp-controller="ChronicMedication" asp-action="">Book Now</a>
        </div>

        <div class="dashboardItem">
            <h2>View Appointments</h2>
            <a asp-controller="ChronicMedication" asp-action="">View Now</a>
        </div>

        <div class="dashboardItem">
            <h2>Medication Refills</h2>
            <a asp-controller="ChronicMedication" asp-action="">Request Refill</a>
        </div>

        <div class="dashboardItem">
            <h2>Prescriptions</h2>
            <a asp-controller="ChronicMedication" asp-action="">View Prescriptions</a>
        </div>

        <div class="dashboardItem">
            <h2>Medication Reminders</h2>
            <a asp-controller="ChronicMedication" asp-action="">Set Reminders</a>
        </div>

        <div class="dashboardItem">
            <h2>Pharmacy Locator</h2>
            <a asp-controller="ChronicMedication" asp-action="">Find Pharmacy</a>
        </div>
    </div>
</body>
</html>

Views/ChronicMedication/MedicationPrescriptionHistory.cshtml
@using System.Data


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient History Report</title>
    <link rel="stylesheet" href="/css/boostrap.css" />
    <link rel="stylesheet" href="/css/site.css?v=pAGv4ietcJNk_EwsQZ5BN9-K4MuNYS2a9wl4Jw-q9D0" />
    <link rel="stylesheet" href="/CodeMed.styles.css?v=6NpGbMrsF9p1j3fx9VpwMIJhHcOU_HqRiXy2MVUSMqI" />
    <link href="assets/img/favicon.jpg" rel="icon" />
    <link href="assets/img/apple-touch-icon.jpg" rel="apple-touch-icon" />
    <style>
        .custom-label {
            width: 150px;
            /* Add any other styles you want for the label here */
        }

        select.form-control {
            width: 150px;
            /* Add any other styles you want for the select element here */
        }

        table {
            max-width: 1237px; /* Set the same max-width as the form */
            margin: 0 auto; /* Center the table within the form */
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #87C1FF;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #87C1FF;
            color: white;
        }

        tr:nth-child(even) {
            background-color: white;
        }

        .centered-button-container {
            display: flex;
            justify-content: center;
        }

        .search-and-select {
            display: flex;
            align-items: center;
        }

        /* Style the search input to make it inline with the dropdown */
        #search_patient {
            margin-left: 10px; /* Add space between the select and input */
        }

        button.custom-button {
            width: 400px; /* Set the width to 200px */
        }

        .center {
            text-align: center;
            color: #36517E;
        }

        .blank-line {
            margin-bottom: 80px; /* Adjust the value as needed */
        }

        button {
            background-color: #4CAF50;
            color: white;
            padding: 10px;
            border: none;
            border-radius: 5px;
            box-shadow: 1px 1px 5px grey;
            cursor: pointer;
            display: flex;
            justify-content: center;
            width: 200px;
        }

            button:hover {
                background-color: #3e8e41;
            }

        div {
            margin-bottom: 10px;
        }

        .centered-button-container {
            display: flex;
            justify-content: center;
        }

        button.custom-button {
            width: 200px; /* Set the width to 200px */
        }

        .button-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
        }

            .button-container button {
                flex: 1;
                margin-right: 10px;
            }

        .center {
            text-align: center;
            color: #36517E;
        }

        .blank-line {
            margin-bottom: 80px; /* Adjust the value as needed */
        }


        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }


        form {
            max-width: 1300px;
            margin: 0 auto;
            text-align: left;
            padding: 20px; /* Add padding within the border */
            position: relative;
        }

            form::before {
                content: "";
                position: absolute;
                top: -2px;
                right: -2px;
                bottom: -2px;
                left: -2px;
                border: 2px solid #36517E; /* Outer border */
                border-radius: 5px;
                pointer-events: none; /* Ensure the outer border doesn't interfere with the form */
            }

            form::after {
                content: "";
                position: absolute;
                top: 2px;
                right: 2px;
                bottom: 2px;
                left: 2px;
                border: 2px solid #36517E; /* Inner border */
                border-radius: 5px;
                pointer-events: none; /* Ensure the inner border doesn't interfere with the form */
            }

            form label {
                display: block;
                margin-bottom: 10px;
                color: #36517E;
                font-weight: bold;
            }

            form input[type="text"],
            form input[type="tel"],
            form input[type="email"],
            form input[type="date"],
            form input[type="time"],
            form textarea,
            form select,
            form input[type="submit"] {
                width: 100%;
                padding: 8px;
                border: 1px solid #ccc;
                border-radius: 3px;
                margin-bottom: 15px;
                font-size: 14px;
            }

            form input[type="submit"] {
                background-color: #36517E;
                color: #fff;
                border: none;
                padding: 10px 20px;
                cursor: pointer;
                font-size: 16px;
                border-radius: 3px;
            }

                form input[type="submit"]:hover {
                    background-color: #243d5e;
                }
    </style>
</head>
<body>

    <div class="blank-line"></div>

    <div class="container">
       
        <form method="post">
            <div class="center">
                <h1>CodeMed – e-Nompilo Primary Healthcare</h1>
            </div>
            <div class="center">
                <img src="~/images/CodeMed_Logo.jpg" width="50" height="50" />
            </div>

            <div class="center">
                <h1>Patient History Report</h1>
            </div>
            <p><i class="fas fa-calendar-alt"></i> Doctor Name: @($"{Context.Session.GetString("FirstName")} {Context.Session.GetString("LastName")}")</p>

            <table style="width: 150%; margin-left: 0%;">
                <thead>
                    <tr>
                        <th width="13%">Patient Name</th>
                        <th width="13%">Chronic Condition</th>
                        <th width="13%">Medication Name</th>
                        <th width="13%">Dose</th>
                        <th width="10%">Routes of Administration</th>
                        <th width="10%">Warning</th>
                        <th width="10%">Special Instructions</th>
                        <th width="13%">Prescription Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DataRow row in Model.Rows)
                    {
                        <tr>
                            <td>@row["PatientName"]</td>
                            <td>@row["ChronicCondition"]</td>
                            <td>@row["MedicationName"]</td>
                            <td>@row["Dose"]</td>
                            <td>@row["RoutesOfAdministration"]</td>
                            <td>@row["Warning"]</td>
                            <td>@row["SpecialInstructions"]</td>
                            <td>@row["PrescriptionDate"]</td>
                        </tr>
                    }
                </tbody>
            </table>
        </form>
    </div>


    <script>
        document.getElementById("filterDropdown").addEventListener("change", function () {
            var selectedOption = this.value;
            switch (selectedOption) {
                case "option1":
                    // Do nothing or show a message for the "Select Option" case.
                    break;
                case "option2":
                    window.location.href = "/ChronicMedication/MedicationReport";
                    break;
                case "option3":
                    window.location.href = "/ChronicMedication/DoctorTotalPrescriptions";
                    break;
                case "option4":
                    window.location.href = "/ChronicMedication/MostPrescribed";
                    break;
                case "option5":
                    window.location.href = "/ChronicMedication/MedicationPrescriptionHistory";
                    break;
            }
        });
    </script>


    <!-- Visual Studio Browser Link -->
    <script type="text/javascript" src="/_vs/browserLink" async="async" id="__browserLink_initializationData" data-requestId="3aa194dc80c2412e81d75fa58896a32f" data-requestMappingFromServer="false" data-connectUrl="http://localhost:50570/d944ef8df85f4fe386ed323d0d014d88/browserLink"></script>
    <!-- End Browser Link -->

    <script src="/_framework/aspnetcore-browser-refresh.js"></script>
</body>
</html>

Views/ChronicMedication/PatientMedication.cshtml
@{
    ViewData["Title"] = "PatientMedication";
}

<h1>PatientMedication</h1>

Views/ChronicMedication/Performance.cshtml
@{
    ViewData["Title"] = "Performance";
}

<h1>Performance</h1>

Views/ChronicMedication/PrescriptionAnalysis.cshtml
@{
    ViewData["Title"] = "PrescriptionAnalysis";
}

<h1>PrescriptionAnalysis</h1>